# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 14:41
from __future__ import unicode_literals

from django.db import migrations
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diaryuser',
            managers=[
                ('objects', member.models.DiaryUserManager()),
            ],
        ),
    ]
